import sys
from PyQt5.QtWidgets import *

######## SIGNAL AND SLOTS ###############
# Signal 
#     they are generated by the Widgets, all Widgets are inherited from QWidget
#     and some of its childs(QButton, QSlider, ...) is the source of signals in response to an event.
# Slot
#     a slot is a python call back function which is called when a signal
#     is received.

def window():
   app = QApplication(sys.argv)
   # QApplication can receive command line arguments `sys.argv`
   # what arguments can be? leve it for now
   win = QDialog()
   # comming next........

   b1 = QPushButton(win)
   # instintiate a button and provede QDialog to it
   b1.setText("Button1")
   b1.move(50,20)
   b1.clicked.connect(b1_clicked)
   # clicked is a singal
   # bi_clicked is a slot
   # and the connect method establish connection between them
   
   b2 = QPushButton(win)
   b2.setText("Button2")
   b2.move(50,50)
   b2.clicked.connect(b2_clicked)
   
   win.setGeometry(100,100,200,100)
   win.setWindowTitle("PyQt5")
   win.show()

   sys.exit( # perfoms clean up and deallocate any allocated resources
      app.exec_() # starts and exit(when crossed button is clicked) the event loop 
   ) # it is also good practice to use sys.exit() and not only app.exec_()

def b1_clicked():
   # the call back will be called when button is pressed.
   print ("Button 1 clicked")

def b2_clicked():
   print ("Button 2 clicked")


window()
# show window